### ISSUE TITLE
undefined method vote_weight

### ISSUE THREAD

**Issue by rahul100885** [ryanto/acts_as_votable#58]
I am getting following error on version 0.8.0

MethodError (undefined method `vote_weight=' for #ActsAsVotable::Vote:0x00000008f70488)

on 

@comment.liked_by @user

But same thing is working in 0.7.1

Any specific change do I need to do?
